pipeline {
    agent any

    stage('tests') {
        steps {
            echo "Running tests in a fully containerized environment..."
            dir ('../') {
                sh './run_tests.sh'
            }
        }
    }

    always {
      cleanWs()
    }
}